<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticleAccueil(){
        $query = $this->getEntityManager()
            ->createQuery("SELECT a FROM AppBundle:Article a ORDER BY a.id DESC");
            $query->setMaxResults(3);
        return $query->getResult();
    }
}
