<?php

namespace AppBundle\Repository;

/**
 * BdVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BdVRepository extends \Doctrine\ORM\EntityRepository
{
}
