<?php

namespace AppBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{

    public function ventesTotales()
    {
        $query = $this->createQueryBuilder('c')
        ->where ('c.vente is not null')
        ->join('c.VehiculePhysique', 'v', 'WITH', 'c.id = v.id');
        
       
        $ventesTotales = $query->getQuery()->getResult();

        
        return $ventesTotales;
    }

    public function test()
    {

        $dql = 'SELECT c FROM AppBundle:Cart c JOIN AppBundle:VehiculePhysique v';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();

    }

}
