<?php

namespace AppBundle\Repository;

/**
 * CartContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartContentRepository extends \Doctrine\ORM\EntityRepository
{
}
