<?php

namespace AppBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{


// Recuperation des ventes totales 

    public function ventesTotales()
    {
        $dql = 'SELECT c FROM AppBundle:Cart c where c.vente is not null order by c.dateMiseAuPanier ASC';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();
    }

// Recuperation des ventes annuelles
    public function ventesAnnuelles($debutAnnee, $finAnnee)
    {
        $query = $this->createQueryBuilder('c')
                 ->where('c.vente is not null')
                 ->andWhere('c.dateMiseAuPanier BETWEEN :debutAnnee AND :finAnnee')
                 ->orderBy('c.dateMiseAuPanier', 'ASC')
                 ->setParameter('debutAnnee', $debutAnnee.'0101')  
                 ->setParameter('finAnnee', $finAnnee.'1231')
                 ->getQuery();

        return $query->getResult();         
    }

    // Recuperation des ventes 1er trimestre
    public function ventesTrimUn($premierTriDeb, $premierTriFin)
    {
        $query = $this->createQueryBuilder('c')
                 ->where('c.vente is not null')
                 ->andWhere('c.dateMiseAuPanier BETWEEN :premierTriDeb AND :premierTriFin')
                 ->setParameter('premierTriDeb', $premierTriDeb.'0101')  
                 ->setParameter('premierTriFin', $premierTriFin.'0331')
                 ->orderBy('c.dateMiseAuPanier', 'ASC')
                 ->getQuery();

        return $query->getResult();         
    }

}
