<?php

namespace AppBundle\Repository;

/**
 * CategorieOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
