<?php

namespace AppBundle\Repository;

/**
 * ConcessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcessionRepository extends \Doctrine\ORM\EntityRepository
{
}
