<?php

namespace AppBundle\Repository;

/**
 * CouleurDisponibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurDisponibleRepository extends \Doctrine\ORM\EntityRepository
{
}
