<?php

namespace AppBundle\Repository;

/**
 * DemandeEssaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEssaiRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEssaiByConcession($concession){
        return $this->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:DemandeEssai d WHERE d.concession = $concession ORDER BY d.dateDemande ASC")
            ->getResult();
    }
}
