<?php

namespace AppBundle\Repository;

/**
 * DemandeEssaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEssaiRepository extends \Doctrine\ORM\EntityRepository
{
}
