<?php

namespace AppBundle\Repository;

/**
 * DemandeEssaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEssaiRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEssaiByConcession($concession){
        return $this->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:DemandeEssai d WHERE d.concession = $concession ORDER BY d.dateDemande ASC")
            ->getResult();
    }

    public function findEssaiEnAttenteByConcession($concession){
        return $this->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:DemandeEssai d WHERE d.concession = $concession AND d.statutMailEssai != 'Demande traitée' OR d.statutMailEssai IS NULL ORDER BY d.dateDemande ASC")
            ->getResult();
    }

    public function findEssaiTraiteByConcession($concession){
        return $this->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:DemandeEssai d WHERE d.concession = $concession AND d.statutMailEssai = 'Demande traitée' ORDER BY d.dateDemande ASC")
            ->getResult();
    }

    public function findEssaiEnAttente(){
        return $this->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:DemandeEssai d WHERE d.statutMailEssai != 'Demande traitée' OR d.statutMailEssai IS NULL ORDER BY d.dateDemande ASC")
            ->getResult();
    }

    public function findEssaiTraite(){
        return $this->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:DemandeEssai d WHERE d.statutMailEssai = 'Demande traitée' ORDER BY d.dateDemande ASC")
            ->getResult();
    }
}
