<?php

namespace AppBundle\Repository;

/**
 * GroupeConcessionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeConcessionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
