<?php

namespace AppBundle\Repository;

/**
 * ModeDeLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeDeLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
