<?php

namespace AppBundle\Repository;

/**
 * VehicleOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
