<?php

namespace AppBundle\Repository;

/**
 * VehiclesValidationStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiclesValidationStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
