<?php

namespace AppBundle\Repository;

/**
 * VehiclePhyStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiclePhyStatutRepository extends \Doctrine\ORM\EntityRepository
{

}
