<?php

namespace AppBundle\Repository;

/**
 * VehiclesValidationStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiclesValidationStatutRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStatutVendu(){
        return $this->getEntityManager()
            ->createQuery("SELECT v FROM AppBundle:VehiclesValidationStatut v WHERE v.statut IN ('Vendu')")
            ->getResult();
    }
}

