<?php

namespace AppBundle\Repository;

/**
 * VehiculePhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculePhysiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
