<?php

namespace AppBundle\Repository;

/**
 * VehicleDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVehDefById($id) {
        return $this->getEntityManager()
            ->createQuery("SELECT v FROM AppBundle:VehicleDefinition v WHERE v.id = $id")
            ->getResult();
    }

    public function findLastThree(){
        $query = $this->getEntityManager()
            ->createQuery("SELECT a FROM AppBundle:VehicleDefinition a ORDER BY a.id DESC");
        $query->setMaxResults(3);
        return $query->getResult();
    }

    public function findByMarque($marque){
        $query = $this->getEntityManager()
            ->createQuery("SELECT v FROM AppBundle:VehicleDefinition v WHERE v.marque = $marque");
        return $query->getResult();
    }

    public function findByType($type){
        $query = $this->getEntityManager()
            ->createQuery("SELECT v FROM AppBundle:VehicleDefinition v WHERE v.typeVehicule = $type");
        return $query->getResult();
    }

    public function findByEnergy($energy){
        $query = $this->createQueryBuilder('v')
            ->join('v.version', 'ver')
            ->join('ver.energie', 'e');

        $query->where('e.id = :$energy')
                ->setParameters(array(
                    '$energy' => $energy,
                    )
                );
    }
}
